# Generated by Django 4.2.6 on 2023-12-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_description_alter_thing_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
